server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: info, trace

  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always