server:
  port: 8080

spring:
  application:
    name: spring-boot-prometheus-demo

management:
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application : ${spring.application.name}

  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
